=== eomjinyoung/bitcamp-20191202/bitcamp-docs/xml/test01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student*,student2*)>
<!ELEMENT student (type?,name,age,tel*,school+)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT school (name,grade)>
<!ELEMENT grade (#PCDATA)>

<!ELEMENT student2 EMPTY>
<!ATTLIST student2
  type (일반|직장인|재학생) "일반"
  name CDATA #REQUIRED
  age CDATA #REQUIRED
  tel CDATA #IMPLIED
>

=== eomjinyoung/bitcamp-20191202/bitcamp-docs/xml/test01.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE students PUBLIC "-//bitcamp//student dtd 1.0//EN" "test01.dtd">

<students xmlns:s="http://bitcamp.co.kr/java300/students">
  <student>
    <type>일반</type>
    <name>홍길동</name>
    <age>20</age>
    <tel>1111-1111</tel>
    <tel>1111-1111</tel>
    <tel>1111-1111</tel>
    <school>
      <name>한국대학교</name>
      <grade>대학교</grade>
    </school>
    <school>
      <name>한국고등학교</name>
      <grade>고등학교</grade>
    </school>
  </student>
  
  <student2 type="재학생" name="홍길동" age="20" tel="1111-1111"/>
  
</students>
